### ISSUE TITLE
Most commands don't work

### ISSUE THREAD

**Issue by Havanacus** [thebrightspark/Land-Manager#4] opened 2019-03-14 02:36 UTC
Minecraft: 1.12.2
Forge: 14.23.5.2768
LandManager: 1.2.0

I'm trying to use the mod for the first time so maybe I'm doing something wrong, but after testing in an instance with no other mods I'm pretty sure this is some kind of bug.

I'm able to make an Area with the Admin Tool and use the /lm claim, /lm area, /lm areas, /lm show, and /lm showoff commands.  These are also the only commands listed when I use /lm.  Every other command listed on [this page of the github wiki](https://github.com/thebrightspark/Land-Manager/wiki/Commands) doesn't work for me. Using them produces no results, nothing in chat, and nothing in the forge logs. The /lm tool command doen't even give an Admin Tool.

Possibly related, there is no permissions category in the config file as described in the "Optional Commands" section of the Wiki.

I apologize ahead of time if this is just me not knowing how to use the mod.

**Comment by thebrightspark** [comment] 2019-03-14 08:11
Sorry not a bug, just I created that wiki page a little ahead of my next release - so my bad, sorry! I'd hoped the next release would by out by now but other things have prevented me from doing so.

There's some commands there that will work if you used `lmop <command>` instead, but a couple of them are new and so won't do anything yet. Likewise, some of the configs are also new.

**Comment by thebrightspark** [comment] 2019-05-06 10:48
Closing this now as the mod has been updated since which match with the wiki

**Closed by thebrightspark** 2019-05-06 10:48 UTC
